# Generated by Django 2.1.7 on 2021-03-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('remark', models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注')),
                ('number', models.CharField(help_text='客户编号', max_length=8, verbose_name='客户编号')),
                ('name', models.CharField(help_text='客户名称', max_length=32, verbose_name='客户名称')),
                ('abbr', models.CharField(default=' ', help_text='客户简介', max_length=64, verbose_name='客户简介')),
                ('address', models.CharField(default=' ', help_text='客户地址', max_length=256, verbose_name='客户地址')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'tb_client',
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientBelong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('remark', models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注')),
                ('belong', models.CharField(max_length=32, verbose_name='客户所属')),
            ],
            options={
                'verbose_name': '客户所属',
                'verbose_name_plural': '客户所属',
                'db_table': 'tb_client_belong',
            },
        ),
        migrations.CreateModel(
            name='ClientIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('remark', models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注')),
                ('industry', models.CharField(max_length=32, verbose_name='所属行业')),
            ],
            options={
                'verbose_name': '所属行业',
                'verbose_name_plural': '所属行业',
                'db_table': 'tb_client_industry',
            },
        ),
        migrations.CreateModel(
            name='ClientMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('remark', models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注')),
                ('mark', models.CharField(max_length=32, verbose_name='客户等级')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'tb_client_mark',
            },
        ),
        migrations.CreateModel(
            name='ClientProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('remark', models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注')),
                ('type', models.CharField(max_length=32, verbose_name='产品所属类型')),
            ],
            options={
                'verbose_name': '产品所属类型',
                'verbose_name_plural': '产品所属类型',
                'db_table': 'tb_client_product_type',
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('remark', models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注')),
                ('type', models.CharField(max_length=32, verbose_name='客户类型')),
            ],
            options={
                'verbose_name': '客户类型',
                'verbose_name_plural': '客户类型',
                'db_table': 'tb_client_type',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ClientBelong'),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ClientIndustry', verbose_name='客户性质'),
        ),
        migrations.AddField(
            model_name='client',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ClientMark', verbose_name='客户等级'),
        ),
        migrations.AddField(
            model_name='client',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ClientProductType', verbose_name='产品行业'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ClientType', verbose_name='客户类型'),
        ),
    ]
