# Generated by Django 2.1.7 on 2021-03-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('number', models.CharField(max_length=32, verbose_name='设备编号')),
                ('name', models.CharField(max_length=32, verbose_name='设备名称')),
                ('size', models.CharField(max_length=32, verbose_name='设备尺寸')),
                ('power', models.CharField(max_length=16, verbose_name='功耗')),
                ('materials', models.CharField(max_length=16, verbose_name='材料')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'tb_equipment',
            },
        ),
        migrations.CreateModel(
            name='Idle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('status', models.CharField(max_length=16, verbose_name='状态')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
                'db_table': 'tb_equipment_status',
                'ordering': ['status', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('process', models.CharField(max_length=16, verbose_name='工序')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'db_table': 'tb_equipment_process',
                'ordering': ['process', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessesKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('kind', models.CharField(max_length=16, verbose_name='工序种类')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Processes')),
            ],
            options={
                'verbose_name': '工序种类',
                'verbose_name_plural': '工序种类',
                'db_table': 'tb_equipment_process_kind',
                'ordering': ['kind', '-id'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='idle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Idle', verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Processes', verbose_name='设备所属工序'),
        ),
    ]
