# Generated by Django 2.1.7 on 2021-03-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20210321_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='idle',
            name='remark',
            field=models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='processes',
            name='remark',
            field=models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='processeskind',
            name='remark',
            field=models.CharField(default=' ', help_text='备注', max_length=256, verbose_name='备注'),
        ),
    ]
