# Generated by Django 2.1.7 on 2021-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltna',
            name='new_salt_thaw_craft',
            field=models.CharField(max_length=256, verbose_name='新盐化盐融化工艺'),
        ),
        migrations.AlterField(
            model_name='saltna',
            name='using_salt_thaw_craft',
            field=models.CharField(max_length=256, verbose_name='新盐实用融化工艺'),
        ),
    ]
