# Generated by Django 2.1.7 on 2021-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0003_auto_20210321_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltcheck',
            name='cn',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='氰根浓度', max_digits=5, null=True, verbose_name='氰根浓度'),
        ),
        migrations.AlterField(
            model_name='saltcheck',
            name='cno',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='氰酸根浓度', max_digits=5, null=True, verbose_name='氰酸根浓度'),
        ),
        migrations.AlterField(
            model_name='saltcheck',
            name='co3',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='碳酸根浓度', max_digits=5, null=True, verbose_name='碳酸根浓度'),
        ),
        migrations.AlterField(
            model_name='saltclient',
            name='cn',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='氰根浓度', max_digits=5, null=True, verbose_name='氰根浓度'),
        ),
        migrations.AlterField(
            model_name='saltclient',
            name='cno',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='氰酸根浓度', max_digits=5, null=True, verbose_name='氰酸根浓度'),
        ),
        migrations.AlterField(
            model_name='saltclient',
            name='co3',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='碳酸根浓度', max_digits=5, null=True, verbose_name='碳酸根浓度'),
        ),
        migrations.AlterField(
            model_name='saltnew',
            name='cn',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='氰根浓度', max_digits=5, null=True, verbose_name='氰根浓度'),
        ),
        migrations.AlterField(
            model_name='saltnew',
            name='cno',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='氰酸根浓度', max_digits=5, null=True, verbose_name='氰酸根浓度'),
        ),
        migrations.AlterField(
            model_name='saltnew',
            name='co3',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='碳酸根浓度', max_digits=5, null=True, verbose_name='碳酸根浓度'),
        ),
    ]
